[package]
name = "tcp-client"
version = "0.1.0"
authors = ["thesylex"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.18.0"
rand = "0.7"
